spring:
  #spring.datasource:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.38.178/sell?characterEncoding=utf-8&useSSL=false
  #spring.jpa:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  #spring.redis:
  redis:
    host: 192.168.38.178
    port: 6379
    password:
  #spring.jackson:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  #spring.mvc
  mvc:
    view:
      suffix: .ftl
  #spring.freemarker
  freemarker:
    cache: false

server:
  port: 80
  context-path: /sell


wechat:
  mpAppId: wx68d02101e4c85515
  mpAppSecret: 71e1f49fa5f9983b16d0620b4df888cd
  natappUrl: http://sellsell.s1.natapp.cc
  templateId:
    orderStatus: t5jEP6-WWkL-e9IVxwqXIm7lz38Hwnn9iDTvBF31OKg

projectUrl:
  sell: http://sellsell.s1.natapp.cc